### ISSUE TITLE
@for

### ISSUE THREAD

**Issue by YouTwitFace** [hkh12/spreax#1]
It would be nice to be able to use `@for="item of items"`. Example:

```javascript
items = [
    'Item 1',
    'Item 2'
];
```

```html
<div>
    <label @for="item of items">@(item)</label>
</div>
```

Which would output:

```html
<div>
    <label>Item 1</label>
    <label>Item 2</label>
</div>
```

**Comment by Hkh12** [comment]
Yes, it's a good idea. I had it in mind from the beginning of the project, but it's a little bit hard to implement in this library.
We have to add "extra" context (`{ item: 'Item 1', i: 0 }`) to elements and some parts should be re-written to work with this. I'll try!

**Comment by YouTwitFace** [comment]
I've written [this](https://gist.github.com/YouTwitFace/f5540f54900baebd45d6104bedc7c7e5)... not sure if this is very good.

**Comment by Hkh12** [comment]
I tested it and it didn't work :confused: To make it parse the children you should've done this:
```js
getAllNodes(element).forEach(node => this.$handleNode(node))
```
---
As my idea, every node has a dedicated context and every context object has its own event system. 
```js
class Context {
  $on(...) {}
  $emit(...) {}
}
```
`this.$ctx` will be a global context, and it can control every node's context. When a node is passed to `$handleNode`, `$ctx` will take the node's context under its control. I can't guarantee that it would succeed :no_mouth: Let's see what happens!

**Comment by YouTwitFace** [comment]
Oh, thanks. Would be great if you can implement it.

**Comment by Hkh12** [comment]
Well, I tried and I couldn't do it :disappointed:
I'm a bit busy these days because of the exams... This issue remains open and maybe I'll try again to implement it in the later versions.

**Comment by hkh12** [comment]
Good news: I'm working on a rewrite of Spreax using TypeScript. `@for` included. :eyes:

**Comment by hkh12** [comment]
Closing for now.
