### ISSUE TITLE
`@for` directive called with `undefined`

### ISSUE THREAD

**Issue by YouTwitFace** [hkh12/spreax#8]
The `@for` directive is always called with `undefined`, causing actions to break if it doesn't check for `undefined`.

Reproducible example: https://codesandbox.io/s/bold-cloud-r3d1g
Version: latest commit (aeadf81)

**Comment by hkh12** [comment]
After rendering all items, the original element doesn't get completely removed:
```js
const xs = state([1, 2, 3]);
```
```html
<div @for="x of xs">@(x)</div>
```
We have 3 elements rendered here, but actually 4 wrappers are initialized. The fourth one doesn't have `x` in its context, and this causes the error.

**Comment by hkh12** [comment]
Fixed.
