### ISSUE TITLE
Adding multiple `@on` directives only adds one handler

### ISSUE THREAD

**Issue by YouTwitFace** [hkh12/spreax#9]
### Bug description

Adding multiple `@on` directives only adds one handler

### Steps to reproduce
- Add multiple `@on` handlers (e.g. `keydown`, `keyup`)

### Expected behavior

All handlers should be added

### Information

 - Browser: Chrome 79
 - Version: 2.1.0 (f8aa174)

### Additional context

https://csvs1.csb.app

**Comment by hkh12** [comment]
@YouTwitFace 😑🤦‍♂
